spring:
  profiles:
    active: local
server:
  port: 8082
restClient:
  moviesInfoUrl: http://localhost:8080/v1/movieinfos
<<<<<<< HEAD
  reviewsUrl: http://localhost:8081/v1/reviews
=======
  reviewsUrl: http://localhost:8081/v1/reviews
>>>>>>> b5644d1 (added the appl yml)
